version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/appdb
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=appdb
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "./wait-for-it.sh db && 
            python create_migration.py &&
            python setup_alembic.py &&
            alembic upgrade head &&
            uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=appdb
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
